apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-ckhg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/rhtap-demo-zrcx-tenant/e2e-dotnet/devfile-sample-dotnet60-basic-ckhg@sha256:288ddc15fad908e76171649b356858b49969b6b5d07939d019bb6106f5950faa
        name: main
        resources: {}
status: {}
